name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set release version version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.tag }} --batch-mode

      - uses: EndBug/add-and-commit@v9
        with:
          message: Release ${{ github.event.inputs.tag }}
          add: |
            - pom.xml
            - energy-meter-api/pom.xml
          default_author: github_actions

      - name: Create branch and tag for new release
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
          git checkout -b ${{ github.event.inputs.tag }}
        
      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Push new tag
        run: |
          git push --set-upstream origin refs/heads/${{ github.event.inputs.tag }}:refs/heads/${{ github.event.inputs.tag }}  
          git push --tags origin HEAD:master
          git checkout origin/master

      - name: Set next snapshot version
        run: mvn versions:set -DnextSnapshot=true -DnextSnapshotIndexToIncrement=3 --batch-mode

      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump to the next SNAPSHOT
          add: |
            - pom.xml
            - energy-meter-api/pom.xml
          default_author: github_actions

      - name: Push new version to Github
        run: |
          git push origin HEAD:master
          
      - name: Tag release on Github
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }} Release
          draft: false
          prerelease: true
